version: "3.8"
services:
  eureka-service:
    container_name: eureka-service
    image: josemiguelchvz/eureka-service:latest
    ports:
      - "8761:8761"
  gateway-service:
    container_name: gateway-service
    image: josemiguelchvz/gateway-service:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
    links:
      - eureka-service
  employee-service:
    container_name: employee-service
    image: josemiguelchvz/employee-service:latest
    ports:
      - "31231:8181"
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
    deploy:
        restart_policy:
          condition: on-failure
    depends_on:
      - eureka-service
    links:
      - eureka-service
  report-service:
    container_name: report-service
    image: josemiguelchvz/report-service:latest
    ports:
      - "31438:8282"
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
    deploy:
        restart_policy:
          condition: on-failure
    depends_on:
      - eureka-service
    links:
      - eureka-service